### ISSUE TITLE
Redundant time(void) method

### ISSUE THREAD

**Issue by baruch** [nicciniamh/WifiNTP#1]
Since you have a time(long) with a default argument of -1 the time(void) method is redundant and only costs space and time for no good reason. The compiler will anyway translate any time() method call to a time(-1) by way of the default argument.

This pattern repeats in many Arduino libraries and I just thought it might be a good idea to notify you that this is not really needed.

**Comment by nicciniamh** [comment]
Thanks!

**Comment by nicciniamh** [comment]
I have removed the redundant code in WiFiNTP.cpp, WiFiNTP.h and updated the readme.
